package com.tazzzo.app.config

import com.tazzzo.app.BuildConfig

/** Generated by AGP from `-Ptazzzo.debugRealOrdering` for the debug build type; always false in release. */
actual fun debugRealOrderingRequested(): Boolean = BuildConfig.DEBUG_REAL_ORDERING
